---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: compiler-web-app # unique key of the deployment instance
spec:
    replicas: 3
    selector:
        matchLabels: # labels are used as mappings in the system
            app: compiler-web-app
    template:
        metadata:
            labels:
                app: compiler-web-app
        spec: # spec for container must have at least one
            containers:
            - name: compiler-web-app # dash used to list
              image: zhanlianguf/compile-web-app:go_1 
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 3000 # number of port to be exposed on the pod's IP address
              livenessProbe: #Under what circumstance is it appropriate to restart the pod
                httpGet:
                    path: /health
                    port: 3000
                    scheme: HTTP
                initialDelaySeconds: 5 # number of seconds after the container has started before liveness probes are initiated
                periodSeconds: 30 # how often in seconds to perform the probe
                timeoutSeconds: 1 # number of seconds after which the probe times out.
              readinessProbe: #designed to let kubernetes know when your app is ready to serve traffic
                httpGet:
                    path: /readiness
                    port: 3000
                    scheme: HTTP
                initialDelaySeconds: 5
                timeoutSeconds: 1
# expose pods to service apiVersion: v1
---
apiVersion: v1
kind: service
metadata:  
    name: compiler-web-app-service
spec:
    type: NodePort # "NodePort" builds on ClusterIP and allocates a port on every node which routes to the same endpoints as the clusterIP.
    ports:
    - name: http
      port: 9090 # the port that will be exposed by the service
      targetPort: 3030 # number of the port to access on the pods targeted by the service
    selector: # Route service traffic to pods with label keys and values matching this selector